package scrumxp;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;

public class AdminFonster extends javax.swing.JFrame {

    private static InfDB idb;
    private static String userID;

    /**
     * Creates new form AdminFonster
     */
    public AdminFonster(InfDB idb, String userID) {
        initComponents();
        this.idb = idb;
        this.userID = userID;
        errorMsg.setText("");
        errorMsgRemoveUser.setText("");
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        firstnameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        picture = new javax.swing.JLabel();
        addButton = new javax.swing.JLabel();
        addUser = new javax.swing.JLabel();
        errorMsg = new javax.swing.JLabel();
        removeUserButton = new javax.swing.JLabel();
        removeUserTitle = new javax.swing.JLabel();
        errorMsgRemoveUser = new javax.swing.JLabel();
        userCombo = new javax.swing.JComboBox<>();
        removeUserButton1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        welcomeText.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        welcomeText.setText(" Välkommen Admin!");

        firstnameField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        firstnameField.setText("Förnamn");
        firstnameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        surnameField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        surnameField.setText("Efternamn");
        surnameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        emailField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        emailField.setText("E-post");
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        usernameField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        usernameField.setText("Användarnamn");
        usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        passwordField.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        passwordField.setText("Lösenord");
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scrumxp/logo_og_sv.png"))); // NOI18N
        picture.setText("jLabel3");

        addButton.setBackground(new java.awt.Color(255, 51, 51));
        addButton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        addButton.setText("   Lägg till");
        addButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        addUser.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        addUser.setText("Lägg till användare");

        errorMsg.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        errorMsg.setText("Felmeddelanden ");

        removeUserButton.setBackground(new java.awt.Color(255, 51, 51));
        removeUserButton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        removeUserButton.setText("    Ta bort");
        removeUserButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        removeUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeUserButtonMouseClicked(evt);
            }
        });

        removeUserTitle.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        removeUserTitle.setText("Ta bort användare");

        errorMsgRemoveUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        errorMsgRemoveUser.setText("Felmeddelanden ");

        userCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboActionPerformed(evt);
            }
        });

        removeUserButton1.setBackground(new java.awt.Color(255, 51, 51));
        removeUserButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        removeUserButton1.setText("   Logga ut");
        removeUserButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        removeUserButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeUserButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(addUser))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errorMsg)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(firstnameField)
                                        .addComponent(surnameField)
                                        .addComponent(emailField)
                                        .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(passwordField)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(userCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(removeUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(errorMsgRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeUserTitle))
                                .addGap(67, 67, 67))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(removeUserButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(welcomeText)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(removeUserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(removeUserButton)
                                .addGap(18, 18, 18)
                                .addComponent(errorMsgRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addButton)
                        .addGap(11, 11, 11)
                        .addComponent(errorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeUserButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        //Samlar in information från textfälten när "lägg till" klickas på med musen
        //Lägger till informationen i databasen 
        if (Validering.textNotEmpty(firstnameField) && Validering.textNotEmpty(surnameField) && Validering.textNotEmpty(emailField) && Validering.textNotEmpty(usernameField) && Validering.textNotEmpty(passwordField)) {
            if (Validering.valideraPassword(passwordField.getText()));
            String firstName = firstnameField.getText();
            String lastName = surnameField.getText();
            String email = emailField.getText();
            String username = usernameField.getText();
            String password = passwordField.getText();
            ArrayList<String> users = null;
            ArrayList<String> emails = null;
            try {
                emails = idb.fetchColumn("SELECT email FROM USERS");
                users = idb.fetchColumn("SELECT USERNAME from users");

            } catch (InfException ex) {
                Logger.getLogger(AdminFonster.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (Validering.isUnique(username, users)) {
                if (Validering.isUnique(email, emails)) {
                    try {
                        String fraga2 = "INSERT INTO USERS (förnamn, efternamn, email, password, username, Admin) VALUES ('" + firstName + " ', '" + lastName + "', '" + email + "', '" + password + "','" + username + "', 'n');";
                        idb.insert(fraga2);
                        JOptionPane.showMessageDialog(null, "Användare har lagts till");
                    } catch (InfException ex) {
                        errorMsg.setText("Databas fel");
                    } catch (NullPointerException ex) {
                        errorMsg.setText("Något gick fel");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Email finns redan, välj en ny");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Username finns redan, välj ett nytt");
            }
        }
    }//GEN-LAST:event_addButtonMouseClicked

    private void removeUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeUserButtonMouseClicked
        //Hämtar objektet som är valt i combo boxen och 
        //tar bort det från databasen när man klickar på "ta bort" knappen
        String userToBeDeleted = userCombo.getSelectedItem().toString();
        String deleteQuery = "DELETE FROM users WHERE förnamn = '" + userToBeDeleted + "';";

        try {
            idb.delete(deleteQuery);
            JOptionPane.showMessageDialog(null, "Användaren togs bort");

        } catch (InfException ex) {
            Logger.getLogger(Calender.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removeUserButtonMouseClicked

    private void userComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userComboActionPerformed

    private void removeUserButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeUserButton1MouseClicked
        //Metod för att logga ut
        if (Validering.checkLogout()) {
            new LoginForm(idb).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_removeUserButton1MouseClicked

    private void fillCombo() {
        //Fyller comboboxen med alla users som inte är admin 
        //Metoden kör i constructorn
        String usersQuery = "SELECT förnamn FROM USERS WHERE Admin NOT LIKE 'J'";
        ArrayList<String> userList;
        try {
            userList = idb.fetchColumn(usersQuery);
            for (String user : userList) {
                userCombo.addItem(user);
            }
        } catch (InfException ex) {
            Logger.getLogger(Calender.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFonster(idb, userID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addButton;
    private javax.swing.JLabel addUser;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel errorMsgRemoveUser;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel removeUserButton;
    private javax.swing.JLabel removeUserButton1;
    private javax.swing.JLabel removeUserTitle;
    private javax.swing.JTextField surnameField;
    private javax.swing.JComboBox<String> userCombo;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
