/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumxp;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author adamnorman
 */
public class SeInlagg extends javax.swing.JFrame {

    private static String id;
    private static InfDB idb;
    private static String userID;
    DefaultTableModel model;

    /**
     * Creates new form SeInlagg
     */
    public SeInlagg(InfDB idb, String id, String userID) {
        this.id = id;
        this.idb = idb;
        this.userID = userID;
        initComponents();
        fyllTextRuta(id);
        model = (DefaultTableModel) jTableKommentarer.getModel();
        hämtaKommentar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableKommentarer = new javax.swing.JTable();
        Textfält = new javax.swing.JTextField();
        Titel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTillbaka = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jKommentar = new javax.swing.JTextArea();
        jButtonFiler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setToolTipText("");
        jScrollPane3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jTableKommentarer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kommentar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableKommentarer.setToolTipText("");
        jScrollPane3.setViewportView(jTableKommentarer);

        Textfält.setEditable(false);
        Textfält.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        Textfält.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfältActionPerformed(evt);
            }
        });

        Titel.setEditable(false);
        Titel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Titel");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Inlägg");

        jTillbaka.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTillbaka.setText("Tillbaka");
        jTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTillbakaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Kommentarer:");

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setText("Publicera kommentar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jKommentar.setColumns(20);
        jKommentar.setRows(5);
        jScrollPane2.setViewportView(jKommentar);

        jButtonFiler.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButtonFiler.setText("Visa filer");
        jButtonFiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTillbaka)
                                .addGap(261, 261, 261)
                                .addComponent(jButtonFiler)
                                .addGap(0, 87, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addContainerGap(95, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Textfält, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Titel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Textfält, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTillbaka)
                    .addComponent(jButtonFiler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextfältActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfältActionPerformed

    }//GEN-LAST:event_TextfältActionPerformed

    private void jTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTillbakaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jTillbakaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     // Lägger till nya kommentarer i databasen. 
        String text = "'" + jKommentar.getText() + "'";
        String kid;
        try {
            kid = idb.getAutoIncrement("KOMMENTARER", "KOMMENTARID");
            String query = "INSERT INTO KOMMENTARER VALUES (" + id + "," + kid + "," + text + ", 'j')";
            System.out.println(query);
            idb.insert(query);
            hämtaKommentar();
            JOptionPane.showMessageDialog(null, "Kommentar har lagts till");
        } catch (InfException ex) {
            Logger.getLogger(skapaKategori.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "fel");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonFilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilerActionPerformed
        //  används för att visa bifogade filer.
        try {
            String pathSql = ("SELECT FIL FROM FILER WHERE INLAGGID = " + id);
            String fil = idb.fetchSingle(pathSql);
            System.out.println(pathSql);
            Desktop.getDesktop().open(new File(fil)); // öppnar upp filen med pathen "fil" som sparats tidigare i databasen.

        } catch (InfException ex) {
            Logger.getLogger(SeInlagg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SeInlagg.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonFilerActionPerformed

    private void fyllTextRuta(String id) {
        try {
            //Hämtar titel och text.
            String titel = idb.fetchSingle("SELECT TITEL FROM INLAGG WHERE INLAGGID = " + id);
            String text = idb.fetchSingle("SELECT INLAGG FROM INLAGG WHERE INLAGGID = " + id);
            Titel.setText(titel);
            Textfält.setText(text);

        } catch (InfException ex) {
            Logger.getLogger(SeInlagg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void hämtaKommentar() {
        // Hämtar kommentarer ur databasen
        ArrayList<String> kommentarlista = new ArrayList();

        try {
            model.setRowCount(0);
            String query = "SELECT KOMMENTARID FROM KOMMENTARER WHERE INLAGGID = " + id;
            kommentarlista = idb.fetchColumn(query);

            for (String kommentar : kommentarlista) {
                String komment = "SELECT KOMMENTAR FROM KOMMENTARER WHERE KOMMENTARID = '" + kommentar + "'";

                model.insertRow(model.getRowCount(), new Object[]{idb.fetchSingle(komment)});
            }
        } catch (InfException ex) {
            Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeInlagg(idb, id, userID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Textfält;
    private javax.swing.JTextField Titel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFiler;
    private javax.swing.JTextArea jKommentar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableKommentarer;
    private javax.swing.JButton jTillbaka;
    // End of variables declaration//GEN-END:variables
}
