/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrumxp;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author adamnorman
 */
public class seMinaInlagg extends javax.swing.JFrame {

    private static InfDB idb;
    private static String id;
    DefaultTableModel model;
    private static String userID;

    /**
     * Creates new form seMinaInlagg
     */
    public seMinaInlagg(InfDB idb, String userID) {
        initComponents();
        this.idb = idb;
        this.userID = userID;
        this.id = id; //InläggsID
        model = (DefaultTableModel) jTable1.getModel();
        hamtaInlagg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTillbaka = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titel", "Användare", "Kategori", "Blogg", "Inläggs ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTillbaka.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTillbaka.setText("Tillbaka");
        jTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTillbakaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scrumxp/logo_og_sv.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTillbaka)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jTillbaka))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Öppnar valt inlägg
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String ide = model.getValueAt(index, 4).toString();

        new UppdateraInlagg(idb, ide, userID).setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTillbakaActionPerformed
        new BloggMeny(idb, userID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void hamtaInlagg() {
        // Hämtar publicerade inlägg
        int i = 0;
        String ide = userID;
        try {

            String antal = idb.fetchSingle("select count(*) from inlagg"); // hämtar antal i string
            int x = Integer.parseInt(antal); // gör om string till int

            while (i <= x) {

                String koll = null;
                String titel = "SELECT TITEL FROM INLAGG WHERE INLAGGID = " + i + " AND ANVANDARE =" + ide;
                String anvandare = "SELECT ANVANDARE FROM INLAGG WHERE INLAGGID = " + i + " AND ANVANDARE =" + ide;
                String kategori = "SELECT KATEGORI FROM INLAGG WHERE INLAGGID = " + i + " AND ANVANDARE =" + ide;
                String blogg = "SELECT BLOGG FROM INLAGG WHERE INLAGGID = " + i + " AND ANVANDARE =" + ide;
                String id = "SELECT INLAGGID FROM INLAGG WHERE INLAGGID = " + i + " AND ANVANDARE =" + ide;
                String kollAnvandare = "SELECT ANVANDARE FROM INLAGG WHERE INLAGGID = " + i;
                koll = idb.fetchSingle(titel); // kontrollerar så det inte är nullvärde

                if (koll != null) { //lägger till rad i tabellen om det inte är null 
                    model.insertRow(model.getRowCount(), new Object[]{idb.fetchSingle(titel), idb.fetchSingle(anvandare),
                        idb.fetchSingle(kategori), idb.fetchSingle(blogg), idb.fetchSingle(id)});

                }
                i++;
            }
        } catch (InfException ex) {
            Logger.getLogger(seBloggInlagg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seMinaInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seMinaInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seMinaInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seMinaInlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seMinaInlagg(idb, userID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jTillbaka;
    // End of variables declaration//GEN-END:variables
}
